# Generated by Django 2.2.1 on 2019-05-03 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('dueDate', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 16, 41, 52, 471866))),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.State')),
            ],
        ),
    ]
