# Generated by Django 2.2.1 on 2019-05-03 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='dueDate',
            field=models.DateField(default=datetime.datetime(2019, 5, 3, 19, 8, 5, 704297)),
        ),
    ]
