# Generated by Django 2.2.1 on 2019-05-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_auto_20190503_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='state',
            new_name='status',
        ),
    ]
