# Generated by Django 2.2.1 on 2019-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_auto_20190505_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('IN-PROGRESS', 'In-progress'), ('DONE', 'Done')], default='TODO', max_length=20),
        ),
    ]
